### ISSUE TITLE
Asking for clarifications

### ISSUE THREAD

**Issue by 3n-mb** [sakurity/securelogin-spec#1]
Given [this doc page](https://github.com/sakurity/securelogin-spec/blob/master/index.md), I want to rephrase it, in step-by-step terms. Please tell me, if anything is missed, misunderstood, or whether I got it right.

1. User visits `site.com`.
There is no prior relationship between user and site.
2. Application on user device and `site.com` do some exchange, generating some secrets, and remembering them on each side respectively.
Client stores its parts under master password.
Server, ... does it store anything? Or, does it rely on signatures generated by some site's long-lived key?
3. When user comes back, app on a device uses stored things to do handshake with `site.com`.
4. `site.com` may share some auth inside of page's friends', depending on scope. Is this right?

Is this understanding correct?
If not, can you tell step by step what happens on first contact, and what happens later.

If these steps are correct representation, then it reminds cookies: something is generated on the first visit, and stored for later identification of site's visitor.
Of cause, this is cookies on crypto steroids, making dev's life a little easier, on one hand. And giving a different control approach for users, on another hand. May be users devices can sync their secret stores, which cookies don't do.

Is my understanding correct? I might be wrong, given slim docs.

**Comment by homakov** [comment]
Hey, spec is not very useful because it's still in-flux.

>Client stores its parts under master password.

No, the client stores nothing important. Everything is deterministic and there's nothing to backup.

The app generates pub key, gives it to website. The client app stores nothing, the website stores pubkey and email, so the user can login to same account again.

Check out new sltoken description for info: https://sakurity.github.io/securelogin-spec/#sec-About-sltoken

It's nothing like cookies. login sltoken (provider==client, empty scope) can be exchanged for session cookie.

**Comment by 3n-mb** [comment]
> Everything is deterministic and there's nothing to backup.

Do you mean that user's private key, for a particular site, shall be *deterministically* generated/calculated via hashing function, like scrypt?
What goes into this calculation? User's master password? Some salt? Is this salt randomly generated on user side at the initial pairing process?

Of cause, this process is clearly mechanically different from cookies. Yet, on a higher level of abstraction, when looking at what parties involved (trust points), it looks like cookies.
Somewhere in the docs you put that this mechanism doesn't guaranty authenticity of user claiming to have a given address. This is like a manual address collection, coupled with cookies, and unlike other processes that involve a third party, an identity provider. This is a level of abstraction in description a developer will look for before proceeding any further.

**Comment by homakov** [comment]
There's no per-site private key. Single key comes from get_keypair(hmac(root, 'shared')) and root is scrypt(email,pw). No other salt but email. https://github.com/sakurity/securelogin/blob/master/js/main.js#L82

I don't see analogy with cookies. Cookies are bearer tokens set by the server to remember user session. sltoken is sent just once to authorize some scope eg login request and can be exchanged for cookies.

**Comment by 3n-mb** [comment]
I see, email serves as salting, and each person's email is presumably different. Good.

>  Cookies are bearer tokens set by the server to remember user session

That's just the mechanism with a long imprint into browsers, with browser session concept. On a higher abstraction, i.e. who is involved, and who trusts who, in my mind, it can be better contrasted with cookies, than three party arrangements. I spent quite a while staring at a diagram, looking for an Identity Provider, which ... isn't there. A cleaner first impression will help PR for this project.
You see, someone looking for IdP, doesn't find, has a predictable negative emotional feedback of a broken expectation. And this fog will let person miss things like scope. Is this intended for sharing info with *friends of site*? It can be interesting.

Thank you for clarifications.

**Comment by homakov** [comment]
You don't see IdP because there is no IdP, and the user is IdP itself w/o central authority. 

Scope = claims - something user visiually approved to do with provider for client. It can be a one off action like do a trade or long term access to locations on provider oauth-style.
